### ISSUE TITLE
Unable to sprint 

### ISSUE THREAD

**Issue by ImperiusOmnis** [kcking/justfly#1]
Hello, thank you so much for making this mod, I loved. Finally a fly mod without using alt to go down hehehe, so I can build better with smart foundations :D

Just found one issue: I'm unable to run on foot, just walk. 

I tried: 
- Enable and disable "hold shift to run".
- Remove and equip Blade Runners.
- Save and reload.

Thank you!

**Comment by kcking** [comment]
Oof yes this is a quick fix -- will have a release out shortly. btw how did you hear about this mod? :D

**Comment by kcking** [comment]
Just published v0.1.1 with this fix, thanks for reporting!

**Comment by ImperiusOmnis** [comment]
Thank you so much :D I loved your mod. I found at ficsit.app web site hehehehe. NP :D
