### ISSUE TITLE
Key mapping

### ISSUE THREAD

**Issue by ghost** [kcking/justfly#2]
Keys seem to be hard-coded to WASD which is only valid on QWERTY keyboards, AZERTY keyboard users would normally use ZQSD instead.
Looking up the game's configurated movement keys could correct the issue here.

**Comment by kcking** [comment]
Thanks for the issue report, I definitely want to fix this to support non-wasd layouts

**Comment by MichaelKim0407** [comment]
It would be nicer to read the game's keybindings if it is possible. I remapped crouching to Left Ctrl so I'd prefer to use that for going down instead of C.

**Comment by kcking** [comment]
I just pushed an update (v0.1.5) that should pull from your configured movement controls. Let me know if this now works!

**Comment by MichaelKim0407** [comment]
@kcking It's perfect, thank you so much!

Also I'd like to let you know that I wouldn't be able to enjoy the game without your mod. Please see details [here](https://steamcommunity.com/app/526870/discussions/0/3004429475633404251/) if you want to know why. It means a lot to me. Thank you again!

**Comment by kcking** [comment]
Glad I could help, thanks for reporting back! :)

**Comment by ghost** [comment]
Seems good to me, does what it says on the box, thank you!
